# Generated by Django 2.1.3 on 2019-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
