# Generated by Django 2.1.3 on 2019-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Demo', '0002_loginuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
