# Generated by Django 2.1.3 on 2019-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Demo', '0003_auto_20191120_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('is_auth', models.IntegerField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
