# Generated by Django 2.1.3 on 2019-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Demo', '0004_auto_20191120_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_email',
            name='auth_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
