# Generated by Django 2.1.3 on 2019-11-21 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Demo', '0005_auth_email_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='create_Time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginuser',
            name='last_login_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间'),
            preserve_default=False,
        ),
    ]
